name: Static Analysis

on: ['push', 'pull_request']

jobs:
  static:
    name: Static Tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
      with:
        php-version: 8.1
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --no-progress --ansi

    - name: Types
      run: composer test:types

    - name: Style
      run: composer test:lint
